version: '3.8'

services:
  # --- INFRAESTRUCTURA DE MENSAJERÍA (KAFKA) ---
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  # Interfaz Web para ver los mensajes en los tópicos (Opcional pero recomendado)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
  # ---MICROSERVICIOS ---
  order-service:
    build:
      context: ./order # Ruta a la carpeta de tu proyecto Order
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:orderdb
    depends_on:
      - kafka
    networks:
      - micro-network

  shipping-service:
    build:
      context: ./shipping # Ruta a la carpeta de tu proyecto Shipping
      dockerfile: Dockerfile
    container_name: shipping-service
    ports:
      - "8082:8082" # Puerto diferente para evitar conflictos
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=shipping-group
    depends_on:
      - kafka
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge